;; p2: 2 jobs x 2 stages x 2 machines (~8 operate groundings). two jobs, crossed routes
(define (problem p2) (:domain jobshop)
  (:objects j1 j2 - job  s1 s2 - stage  m1 m2 - machine)
  (:init
    (next s1 s2)
    (at-stage j1 s1) (final-stage j1 s2)
    (route j1 s1 m1) (= (proctime j1 s1) 4)
    (route j1 s2 m2) (= (proctime j1 s2) 2)
    (at-stage j2 s1) (final-stage j2 s2)
    (route j2 s1 m2) (= (proctime j2 s1) 2)
    (route j2 s2 m1) (= (proctime j2 s2) 3)
    (free m1)
    (free m2)
  )
  (:goal (and (job-complete j1) (job-complete j2))))
