(define (problem alchemy-magic)
  (:domain rpg-world)
  (:objects
    merlin - agent
    sanctum - location)
  (:init
    (at merlin sanctum)
    (mage merlin)
    (has-altar sanctum)
    (is-water sanctum)
    (is-field sanctum)
    (link sanctum sanctum)
    (= (dist sanctum sanctum) 1)
    (= (logs) 0) (= (ore) 0) (= (stone) 0) (= (clay) 0)
    (= (fiber) 0) (= (food) 0) (= (water) 0) (= (herbs) 0)
    (= (planks) 0) (= (charcoal) 0) (= (ingots) 0) (= (blocks) 0)
    (= (bricks) 0) (= (cloth) 0) (= (clothing) 0)
    (= (meals) 0) (= (potions) 0)
    (= (axe-stock) 0) (= (pick-stock) 0) (= (shovel-stock) 0) (= (hammer-stock) 0)
    (= (coin) 0) (= (mana) 0))
  (:goal (>= (potions) 2)))
