(define (problem trade-economy)
  (:domain rpg-world)
  (:objects
    w1 - agent
    hub - location)
  (:init
    (at w1 hub)
    (has-axe w1)
    (is-forest hub)
    (has-sawmill hub)
    (is-market hub)
    (= (dist hub hub) 0)
    (= (logs) 0)
    (= (ore) 0)
    (= (stone) 0)
    (= (clay) 0)
    (= (fiber) 0)
    (= (food) 0)
    (= (water) 0)
    (= (herbs) 0)
    (= (planks) 0)
    (= (charcoal) 0)
    (= (ingots) 0)
    (= (blocks) 0)
    (= (bricks) 0)
    (= (cloth) 0)
    (= (clothing) 0)
    (= (meals) 0)
    (= (potions) 0)
    (= (axe-stock) 0)
    (= (pick-stock) 0)
    (= (shovel-stock) 0)
    (= (hammer-stock) 0)
    (= (coin) 0)
    (= (mana) 0))
  (:goal (>= (coin) 2)))
