//! The generated block inside `README.md`. Port of `_front_rows` + `_patch_readme`.
//!
//! Hand-maintained numbers on a front page drift the moment a sweep lands, and
//! a stale headline is worse than none -- so the shop window is generated from
//! the same data as the table behind it, and [`block`] shares
//! [`RenderCtx::standings`] with `STANDINGS.md` so the two cannot disagree
//! about which boards are in the headline.
//!
//! **The links are ABSOLUTE, and that is an incident.** This block is generated
//! into `README.md`, which ships as the crate README (`readme =
//! "../../README.md"`). crates.io and docs.rs resolve relative links against
//! the CRATE directory, so a bare `STANDINGS.md` there resolves to
//! `crates/ferroplan/STANDINGS.md` and 404s on the published page. Every other
//! link in that README is absolute for the same reason.
//!
//! **[`patch`] never rewrites a README it cannot find both markers in.** It
//! returns `None`, and the caller leaves the file exactly as it was. The
//! alternative -- splicing at whatever offset a failed search produced -- is
//! how a front page gets truncated by a tool that was only asked for a number.

use crate::field::tail4;
use crate::fmt::{self, glyph};
use crate::manifest::CAPABILITIES;
use crate::quality::pref_score;
use crate::raw::RawRow;
use crate::render::{LiveBoard, RenderCtx};
use std::collections::BTreeMap;

/// The opening marker. Deliberately NOT the whole comment: the marker line
/// carries a "generated by ...; do not hand-edit" note after it, and the splice
/// keeps whatever that note currently says rather than reasserting it.
pub const README_BEGIN: &str = "<!-- STANDINGS:BEGIN";
/// The closing marker, whole.
pub const README_END: &str = "<!-- STANDINGS:END -->";

/// The absolute link prefix. Belongs in `benchmarks/manifest.toml` beside the
/// boards -- it is a fact about where this project is published, not about how
/// a table is drawn -- and lives here until `[[board]]`'s file carries a
/// `gh_blob` key. See the module header for why it cannot become a relative
/// path.
pub const GH_BLOB: &str = "https://github.com/hhh42/ferroplan/blob/main/";

/// The table's header: what a reader is looking at, in three words each.
const TABLE_HEAD: [&str; 2] = [
    "| good at | boards (solved/total) | where it ranks, by coverage rate |",
    "|---|---|---|",
];

/// Between two boards in one cell, and between two placements in the next --
/// the same string, so the two cells line up slot for slot.
const SLOT_SEP: &str = " \u{b7} ";

/// Build the block that goes between the markers.
///
/// Since 0.29 the block is a CAPABILITY table (Python `_front_rows`): one row
/// per group in [`CAPABILITIES`] order, each joining its boards' coverage in
/// one cell and their field placements in the next, slot for slot, so a
/// reader matches "2011 240/280" to "2nd of 28 (LAMA-2011 250/280)" by
/// position. A board with no cohort still takes its slot (an em dash). A split
/// cohort (seq-sat 2008 / 2011) is one slot per split, the first carrying the
/// board's name. The preference row carries its IPC points beside its rows,
/// because rows are not what IPC-5 ranked those tracks on and a front page
/// that showed 130/130 alone would be hiding the open gap. The best-five-by-
/// percentage this replaced read ~100 % on every row and said nothing.
///
/// `None` when no board is live: Python's `if not os.path.exists(p) or not
/// tot_n: return` leaves the README untouched rather than replacing a headline
/// with an empty one. A box holding no raws must not blank the front page.
///
/// The returned string both starts and ends with a newline, because the joined
/// list does -- it is spliced directly after the `-->` of the opening marker and
/// directly before the closing marker, and those two newlines are what put each
/// marker on its own line.
pub fn block(ctx: &RenderCtx) -> Option<String> {
    let st = ctx.standings();
    if st.total_rows == 0 {
        return None;
    }

    let mut l: Vec<String> = Vec::new();
    l.push(String::new());

    // No plural switch here, unlike `STANDINGS.md`: the Python's front-page
    // headline says "boards" unconditionally. Ported as written -- the shape of
    // the sentence is published text, and a one-board repository is not a state
    // this project has been in since 0.14.
    let mut headline = format!(
        "**{}% coverage across {} IPC boards** ({}/{}) on `{}`",
        fmt::fmt_f(fmt::pct(st.total_solved, st.total_rows), 0),
        st.live.len(),
        fmt::thousands(st.total_solved as u64),
        fmt::thousands(st.total_rows as u64),
        ctx.box_id.as_str(),
    );
    if st.proofs > 0 {
        headline.push_str(&format!(
            ", including **{} certified optima**.",
            fmt::thousands(st.proofs as u64)
        ));
    } else {
        headline.push('.');
    }
    l.push(headline);

    l.push(String::new());
    l.extend(TABLE_HEAD.iter().map(|s| (*s).to_string()));
    let by_label: BTreeMap<&str, &LiveBoard<'_>> = st.live.iter().map(|r| (r.label, r)).collect();
    for (group, title) in CAPABILITIES {
        if let Some(row) = group_row(ctx, &by_label, group, title) {
            l.push(row);
        }
    }

    l.push(String::new());
    l.push(format!(
        "Rank is by coverage rate against that competition's located entrants, at ~1/30th \
         of the official budget; `~` = entrants unlocated, `{}` = no field data held, {} = \
         coverage is proof rate. **[Full standings {} `STANDINGS.md`]({GH_BLOB}STANDINGS.md)** \
         {} per-track quality and failure classes in \
         [`benchmarks/ipc-standings.md`]({GH_BLOB}benchmarks/ipc-standings.md) {} how the \
         ranks are computed in [`docs/ipc-rankings.md`]({GH_BLOB}docs/ipc-rankings.md).",
        glyph::EM_DASH,
        glyph::SCALES,
        glyph::ARROW,
        glyph::MIDDOT,
        glyph::MIDDOT,
    ));
    l.push(String::new());

    Some(l.join("\n"))
}

/// One capability's row, or `None` when none of its boards is live -- an empty
/// group prints nothing, not a row of dashes.
///
/// Boards come in MANIFEST order (the Python iterates `data`, which is `SWEEPS`
/// order), never by percentage: a front page must not reshuffle between cuts.
fn group_row(
    ctx: &RenderCtx,
    by_label: &BTreeMap<&str, &LiveBoard<'_>>,
    group: &str,
    title: &str,
) -> Option<String> {
    let mut boards: Vec<String> = Vec::new();
    let mut ranks: Vec<String> = Vec::new();
    let mut points: Vec<String> = Vec::new();
    let mut proof = false;
    for b in &ctx.boards {
        if ctx.manifest.capability(&b.label) != Some(group) {
            continue;
        }
        let Some(r) = by_label.get(b.label.as_str()) else {
            continue;
        };
        let short = ctx.manifest.front_name(&b.label);
        proof |= ctx.manifest.is_proof_track(&b.label);
        let cohort = ctx.field.cohort(&b.label);
        if let Some(splits) = cohort.and_then(|c| c.splits.as_ref()) {
            let mut first = true;
            for (ipc, sub) in splits {
                let rs: Vec<&RawRow> = r
                    .rows
                    .iter()
                    .filter(|x| x.ipc.as_deref() == Some(ipc.as_str()))
                    .collect();
                if rs.is_empty() {
                    continue;
                }
                let ss = rs.iter().filter(|x| ctx.referee.is_solved(x)).count();
                let name = if first {
                    format!("{short} {}", tail4(ipc))
                } else {
                    tail4(ipc).to_string()
                };
                first = false;
                boards.push(format!("{name} {ss}/{}", rs.len()));
                ranks.push(
                    sub.placement_brief(ss, rs.len())
                        .unwrap_or_else(|| glyph::EM_DASH.to_string()),
                );
            }
            continue;
        }
        boards.push(format!("{short} {}/{}", r.solved, r.total));
        ranks.push(
            cohort
                .and_then(|c| c.placement_brief(r.solved, r.total))
                .unwrap_or_else(|| glyph::EM_DASH.to_string()),
        );
        // The same test `detail` scores by points with -- Python's
        // `label.endswith("preferences (full corpus)")`.
        if b.label.ends_with("preferences (full corpus)") {
            if let Some(p) = pref_score(r.rows, &ctx.referee, &ctx.archive) {
                points.push(p.brief());
            }
        }
    }
    if boards.is_empty() {
        return None;
    }
    let mut rank_cell = ranks.join(SLOT_SEP);
    if !points.is_empty() {
        rank_cell.push_str("; IPC quality vs SGPlan5 ");
        rank_cell.push_str(&points.join(SLOT_SEP));
    }
    let title = if proof {
        format!("{title} {}", glyph::SCALES)
    } else {
        title.to_string()
    };
    Some(format!(
        "| {title} | {} | {rank_cell} |",
        boards.join(SLOT_SEP)
    ))
}

/// Splice `block` between the README's markers, returning the new text.
///
/// `None` means NOTHING WAS PATCHED and the caller must leave the file alone --
/// the Python's two bare `return`s, which leave the text on disk unchanged.
/// There are three ways to get it, and all three are refusals rather than
/// best-effort writes:
///
/// * either marker is missing (`text.find(...) < 0`);
/// * the opening marker's comment is never closed, so there is no `-->` to
///   splice after. Python computes `text.find("-->", i) + 3` and gets `2` from
///   the miss, then writes `text[:2] + block + text[j:]` -- which deletes the
///   README down to its third byte. That is not a number this port has to
///   reproduce;
/// * the closing marker sits before the end of the opening one, which would
///   splice the block into the middle of its own marker.
///
/// Indices are BYTES, from `str::find`, exactly as Python's `str.find` returns
/// byte offsets into an already-decoded string here. Both markers and `-->` are
/// pure ASCII, so every offset lands on a character boundary by construction.
pub fn patch(readme_text: &str, block: &str) -> Option<String> {
    let i = readme_text.find(README_BEGIN)?;
    let j = readme_text.find(README_END)?;
    let head_end = readme_text[i..].find("-->").map(|k| i + k + 3)?;
    if j < head_end {
        return None;
    }
    let mut out = String::with_capacity(readme_text.len() + block.len());
    out.push_str(&readme_text[..head_end]);
    out.push_str(block);
    out.push_str(&readme_text[j..]);
    Some(out)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::render::tests_support::empty_ctx;

    const README: &str = "# ferroplan\n\
                          \n\
                          <!-- STANDINGS:BEGIN — generated; do not hand-edit -->\n\
                          old headline\n\
                          <!-- STANDINGS:END -->\n\
                          \n\
                          ## Install\n";

    /// The ordinary splice: the block replaces everything between the two
    /// markers, and both markers survive with their own lines intact.
    #[test]
    fn splices_between_the_markers() {
        let out = patch(README, "\nnew headline\n").expect("both markers present");
        assert_eq!(
            out,
            "# ferroplan\n\
             \n\
             <!-- STANDINGS:BEGIN — generated; do not hand-edit -->\n\
             new headline\n\
             <!-- STANDINGS:END -->\n\
             \n\
             ## Install\n"
        );
    }

    /// A missing marker leaves the file alone. `None` is the whole answer: the
    /// caller writes nothing, so the README is unchanged. Splicing at a failed
    /// search's offset is how a front page gets truncated by a tool that was
    /// only asked for a number.
    #[test]
    fn a_missing_marker_patches_nothing() {
        let no_begin = "# ferroplan\n<!-- STANDINGS:END -->\n";
        let no_end = "# ferroplan\n<!-- STANDINGS:BEGIN -->\n";
        let neither = "# ferroplan\n\nnothing generated here.\n";
        assert!(patch(no_begin, "\nx\n").is_none());
        assert!(patch(no_end, "\nx\n").is_none());
        assert!(patch(neither, "\nx\n").is_none());
    }

    /// An opening marker whose comment is never closed has no `-->` to splice
    /// after. Python would write `text[:2] + block + text[j:]` here and take
    /// the README with it.
    #[test]
    fn an_unterminated_opening_marker_patches_nothing() {
        let broken = "# ferroplan\n<!-- STANDINGS:BEGIN oops\n<!-- STANDINGS:END --\n";
        assert!(patch(broken, "\nx\n").is_none());
    }

    /// Markers in the wrong order would splice the block into the middle of the
    /// opening marker itself.
    #[test]
    fn markers_out_of_order_patch_nothing() {
        let reversed = "<!-- STANDINGS:END -->\n<!-- STANDINGS:BEGIN x -->\n";
        assert!(patch(reversed, "\nx\n").is_none());
    }

    /// A multi-byte character before the markers must not shift the splice: the
    /// offsets are BYTES and the text is sliced by bytes, so an em dash in the
    /// heading above the block is invisible to the arithmetic.
    #[test]
    fn multibyte_text_before_the_block_does_not_shift_the_splice() {
        let text =
            "# ferroplan — a planner\n<!-- STANDINGS:BEGIN -->\nold\n<!-- STANDINGS:END -->\n";
        let out = patch(text, "\nnew\n").expect("markers present");
        assert_eq!(
            out,
            "# ferroplan — a planner\n<!-- STANDINGS:BEGIN -->\nnew\n<!-- STANDINGS:END -->\n"
        );
    }

    /// With nothing live there is no block, so the front page keeps whatever it
    /// last said. A box holding no raws must not blank the headline.
    #[test]
    fn no_live_boards_means_no_block() {
        assert!(block(&empty_ctx()).is_none());
    }

    /// The capability table from a hermetic context: a split board renders one
    /// slot per competition with the board's name on the first, a board with
    /// no cohort takes its slot as an em dash, a group with no live board is
    /// not a row, and the block starts and ends with the newline the splice
    /// relies on.
    #[test]
    fn the_capability_table_from_live_rows() {
        use crate::archive::Ipc5Archive;
        use crate::bounds::BestKnownBounds;
        use crate::field::{Cohort, Entrant, FieldBook};
        use crate::history::{BoxId, History};
        use crate::manifest::Manifest;
        use crate::raw::RawRow;
        use crate::referee::Referee;
        use crate::render::tests_support::PREAMBLE;
        use crate::render::{BoardRows, DEFAULT_BOX};

        fn stanza(id: &str, label: &str, extra: &str) -> String {
            format!(
                "\n[[board]]\nid = \"{id}\"\nraw = \"{id}.jsonl\"\nmd = \"{id}.md\"\n\
                 label = \"{label}\"\ncompetition = \"ipc67\"\nbudget_secs = 60\n\
                 track = \"t\"\nrebaselined_on = [\"m5-air\"]\n{extra}"
            )
        }
        fn row(ipc: &str, solved: bool) -> RawRow {
            serde_json::from_str(&format!(
                r#"{{"ipc":"{ipc}","variant":"x","instance":1,"solved":{solved},"val":true}}"#
            ))
            .expect("fixture row parses")
        }
        let src = format!(
            "{PREAMBLE}{}{}{}",
            stanza("ss", "seq-sat", "capability = \"classical\"\n"),
            stanza(
                "s18",
                "2018 seq-sat",
                "capability = \"classical\"\nfront_name = \"2018\"\n"
            ),
            stanza("nb", "net-benefit", "capability = \"preferences\"\n"),
        );
        let manifest = Manifest::parse(&src, "<test>").expect("parses");
        let boards = vec![
            BoardRows {
                id: "ss".into(),
                label: "seq-sat".into(),
                budget_secs: 60.0,
                rows: Some(vec![
                    row("ipc-2008", true),
                    row("ipc-2008", true),
                    row("ipc-2011", true),
                    row("ipc-2011", false),
                ]),
            },
            BoardRows {
                id: "s18".into(),
                label: "2018 seq-sat".into(),
                budget_secs: 60.0,
                rows: Some(vec![row("ipc-2018", false), row("ipc-2018", true)]),
            },
            BoardRows {
                id: "nb".into(),
                label: "net-benefit".into(),
                budget_secs: 60.0,
                rows: None,
            },
        ];
        let mut field = FieldBook::default();
        let mut splits = BTreeMap::new();
        splits.insert(
            "ipc-2008".to_string(),
            Cohort {
                entrants: vec![Entrant {
                    name: "LAMA".into(),
                    solved: 1,
                    of: 2,
                }],
                field_size: Some(3),
                ..Default::default()
            },
        );
        splits.insert(
            "ipc-2011".to_string(),
            Cohort {
                entrants: vec![Entrant {
                    name: "LAMA-2011".into(),
                    solved: 2,
                    of: 2,
                }],
                ..Default::default()
            },
        );
        field.insert_for_test(
            "seq-sat",
            Cohort {
                splits: Some(splits),
                ..Default::default()
            },
        );
        let ctx = RenderCtx::new(
            manifest,
            boards,
            Referee::default(),
            Ipc5Archive::default(),
            BestKnownBounds::default(),
            field,
            History::default(),
            Some("0.29.0".to_string()),
            BoxId::new(DEFAULT_BOX),
        );
        let b = block(&ctx).expect("two live boards render a block");
        assert!(b.starts_with('\n') && b.ends_with('\n'), "{b:?}");
        assert!(
            b.contains(
                "| classical satisficing | seq-sat 2008 2/2 \u{b7} 2011 1/2 \u{b7} 2018 1/2 | \
                 ~1st of 4 (LAMA 1/2) \u{b7} 2nd of 2 (LAMA-2011 2/2) \u{b7} \u{2014} |"
            ),
            "{b}"
        );
        assert!(
            !b.contains("PDDL3 preferences"),
            "an empty group is not a row: {b}"
        );
        assert!(!b.contains("temporal planning"), "{b}");
    }

    /// The published links must be absolute. A relative `STANDINGS.md` resolves
    /// against the CRATE directory on crates.io and docs.rs -- it 404s on the
    /// page most readers actually see.
    #[test]
    fn the_links_are_absolute() {
        assert!(GH_BLOB.starts_with("https://"));
        assert!(GH_BLOB.ends_with('/'));
    }
}
