;; LOGISTICS: the quarry is 2 hops from camp (via a junction); chop at the forest, mine at the quarry, no processing. Stresses durative travel + the derived reachability axiom + multi-site accumulation.
(define (problem logistics-run) (:domain rpg-world)
  (:objects c1 - agent  camp forest junction quarry - location)
  (:init
    (at c1 camp) (has-axe c1) (has-pick c1)
    (is-forest forest) (is-quarry quarry)
    (link camp forest) (link forest camp) (= (dist camp forest) 2) (= (dist forest camp) 2)
    (link camp junction) (link junction camp) (= (dist camp junction) 2) (= (dist junction camp) 2)
    (link junction quarry) (link quarry junction) (= (dist junction quarry) 2) (= (dist quarry junction) 2)
    (= (arrowheads) 0)
    (= (arrows) 0)
    (= (axe-stock) 0)
    (= (bags) 0)
    (= (barrels) 0)
    (= (blocks) 0)
    (= (bone) 0)
    (= (bow-stock) 0)
    (= (bread) 0)
    (= (bricks) 0)
    (= (bronze) 0)
    (= (bullion) 0)
    (= (cargo) 0)
    (= (carry-cap) 0)
    (= (cart-parts) 0)
    (= (carts) 0)
    (= (charcoal) 0)
    (= (clay) 0)
    (= (cloth) 0)
    (= (clothing) 0)
    (= (coal) 0)
    (= (coin) 0)
    (= (copper-ingot) 0)
    (= (copper-ore) 0)
    (= (cut-fittings) 0)
    (= (dairy) 0)
    (= (draughts) 0)
    (= (enchanted-gear) 0)
    (= (fiber) 0)
    (= (fired-pottery) 0)
    (= (fish) 0)
    (= (flour) 0)
    (= (food) 0)
    (= (furniture) 0)
    (= (glass) 0)
    (= (gold-ore) 0)
    (= (grain) 0)
    (= (grain-reserve) 0)
    (= (hammer-stock) 0)
    (= (herbs) 0)
    (= (hide) 0)
    (= (ingots) 0)
    (= (leather) 0)
    (= (leather-armor) 0)
    (= (livestock) 0)
    (= (logs) 0)
    (= (lore) 0)
    (= (mana) 0)
    (= (mana-crystals) 0)
    (= (meals) 0)
    (= (meat) 0)
    (= (ore) 0)
    (= (pack-animals) 0)
    (= (pick-stock) 0)
    (= (pies) 0)
    (= (planks) 0)
    (= (potions) 0)
    (= (pottery) 0)
    (= (ration) 0)
    (= (renown) 0)
    (= (resources) 0)
    (= (sand) 0)
    (= (scrolls) 0)
    (= (seeds) 0)
    (= (shields) 0)
    (= (shovel-stock) 0)
    (= (silver-ore) 0)
    (= (spear-stock) 0)
    (= (spearheads) 0)
    (= (steel) 0)
    (= (stew) 0)
    (= (stone) 0)
    (= (swords) 0)
    (= (timber-frame) 0)
    (= (tin-ingot) 0)
    (= (tin-ore) 0)
    (= (tool-handles) 0)
    (= (water) 0)
    (= (weapon-stock) 0)
  )
  (:goal (and (>= (logs) 3) (>= (stone) 2))))
