;; ============================================================================
;; ferroplan "world" — the universal low-level planning domain for a survival /
;; village-building multiplayer RPG.
;;
;; DESIGN INTENT
;;  * Broad, not deep: many resources, recipes, roles, stations, and entities, so
;;    one domain covers gathering, smithing, woodwork, masonry, textiles, cooking,
;;    alchemy/magic, construction, and trade/contracts.
;;  * Built to DECOMPOSE: an external scheduler carves the world goal into
;;    contract-sized sub-tasks ("make 8 planks", "forge 2 axes", "raise a house")
;;    each given to a worker for a time window. Each sub-task is an easy, NON-
;;    optimal plan — ferroplan just finds *a* way, fast.
;;  * Uses what the engine does well: typing, full ADL (conditional + forall
;;    effects, quantified + disjunctive preconditions, negation), numeric fluents
;;    (graph distances + resource stockpiles), durative actions, and a :derived
;;    reachability axiom over the map.
;;
;; RESOURCE FLOW (each output is producible, each input has a source):
;;   logs ->(saw) planks            logs ->(kiln) charcoal
;;   ore + charcoal ->(smelt) ingots        ingots ->(forge) tools / fittings
;;   stone ->(mason) blocks         clay ->(kiln) bricks
;;   fiber ->(loom) cloth ->(tailor) clothing
;;   food + water ->(cook) meals    herbs + water ->(brew) potions
;;   materials + labor ->(build) structures
;; ============================================================================
(define (domain rpg-world)
  (:requirements :typing :adl :durative-actions :numeric-fluents)

  (:types
    agent location - object
    slot - object)            ; building plots for houses

  (:predicates
    ;; ---- world / movement ----
    (at ?a - agent ?l - location)
    (link ?a ?b - location)          ; a discovered path segment (static)
    (reachable ?a ?b - location)     ; DERIVED: transitive closure of link
    ;; ---- resource sites ----
    (is-forest ?l - location)
    (is-mine ?l - location)
    (is-quarry ?l - location)
    (is-claypit ?l - location)
    (is-water ?l - location)         ; well or river
    (is-pasture ?l - location)
    (is-field ?l - location)
    (is-market ?l - location)
    ;; ---- workstations (a location may host several) ----
    (has-sawmill ?l - location)
    (has-kiln ?l - location)
    (has-forge ?l - location)
    (has-anvil ?l - location)
    (has-mason ?l - location)
    (has-loom ?l - location)
    (has-hearth ?l - location)
    (has-altar ?l - location)
    (is-buildsite ?l - location)
    ;; ---- per-agent tools (persistent, not consumed) ----
    (has-axe ?a - agent)
    (has-pick ?a - agent)
    (has-shovel ?a - agent)
    (has-hammer ?a - agent)
    ;; ---- roles (gate or improve work) ----
    (woodcutter ?a - agent)
    (miner ?a - agent)
    (smith ?a - agent)
    (mason-skill ?a - agent)
    (cook ?a - agent)
    (mage ?a - agent)
    ;; ---- structures / outcomes ----
    (built-house ?s - slot)
    (built-square)
    (built-wall)
    (well-dug)
    (feast-held)
    ;; ===== widened subsystems (predicates) =====
    (has-mill ?l - location)
    (has-granary ?l - location)
    (farmer ?a - agent)
    (tilled ?l - location)
    (planted ?l - location)
    (irrigated ?l - location)
    (is-coalmine ?l - location)
    (is-coppermine ?l - location)
    (is-tinmine ?l - location)
    (is-goldmine ?l - location)
    (is-silvermine ?l - location)
    (metallurgist ?a - agent)
    (baker ?a - agent)
    (well-fed ?a - agent)
    (builder ?a - agent)
    (priest ?a - agent)
    (built-watchtower)
    (built-temple)
    (has-hall ?l - location)
    (workstation)
    (apprentice ?a - agent)
    (master ?a - agent)
    (market-day-held)
    (festival-held)
    (has-tannery ?l - location)
    (has-leather-bench ?l - location)
    (tanner ?a - agent)
    (leatherworker ?a - agent)
    (made-armor)
    (made-bag)
    (has-fletching-bench ?l - location)
    (fletcher ?a - agent)
    (has-barn ?l - location)
    (herder ?a - agent)
    (threat ?l - location)
    (cleared ?l - location)
    (has-weapon ?a - agent)
    (guard ?a - agent)
    (has-trainyard ?l - location)
    (has-watchtower ?l - location)
    (is-sandpit ?l - location)
    (has-wheel ?l - location)
    (potter ?a - agent)
    (has-bow ?a - agent)
    (has-spear ?a - agent)
    (hunter ?a - agent)
    (angler ?a - agent)
    (trap-set ?l - location)
    (has-cartwright ?l - location)
    (has-depot ?l - location)
    (porter ?a - agent)
    (has-cart ?a - agent)
    (carpentry)
    (has-carpenter-bench ?l - location)
    (carpenter ?a - agent)
    (has-enchant-altar ?l - location)
    (has-scribe-desk ?l - location)
    (has-crystal-bed ?l - location)
    (enchanter ?a - agent)
    (injured ?a - agent)
  )

  (:functions
    (dist ?a ?b - location)
    ;; raw materials
    (logs) (ore) (stone) (clay) (fiber) (food) (water) (herbs)
    ;; processed goods
    (planks) (charcoal) (ingots) (blocks) (bricks) (cloth) (clothing)
    (meals) (potions)
    ;; tool stock (forged, then equipped onto an agent)
    (axe-stock) (pick-stock) (shovel-stock) (hammer-stock)
    ;; economy + magic
    (coin) (mana)
    ;; ===== widened subsystems (resources) =====
    (seeds)
    (grain)
    (flour)
    (grain-reserve)
    (copper-ore)
    (tin-ore)
    (gold-ore)
    (silver-ore)
    (coal)
    (copper-ingot)
    (tin-ingot)
    (bronze)
    (steel)
    (bullion)
    (bread)
    (stew)
    (pies)
    (timber-frame)
    (cut-fittings)
    (lore)
    (renown)
    (hide)
    (leather)
    (leather-armor)
    (bags)
    (swords)
    (spearheads)
    (arrowheads)
    (shields)
    (arrows)
    (livestock)
    (dairy)
    (meat)
    (weapon-stock)
    (ration)
    (sand)
    (glass)
    (pottery)
    (fired-pottery)
    (bone)
    (fish)
    (bow-stock)
    (spear-stock)
    (cart-parts)
    (carts)
    (pack-animals)
    (carry-cap)
    (cargo)
    (furniture)
    (barrels)
    (tool-handles)
    (mana-crystals)
    (scrolls)
    (enchanted-gear)
    (draughts)
  )

  ;; ----- DERIVED: reachability over the (static) map -----
  (:derived (reachable ?a ?b - location)
    (or (link ?a ?b)
        (exists (?c - location) (and (link ?a ?c) (reachable ?c ?b)))))

  ;; ========================= MOVEMENT =========================
  (:durative-action travel
    :parameters (?a - agent ?from ?to - location)
    :duration (= ?duration (dist ?from ?to))
    :condition (and (at start (at ?a ?from)) (at start (reachable ?from ?to)))
    :effect (and (at start (not (at ?a ?from))) (at end (at ?a ?to))))

  ;; ========================= GATHERING =========================
  ;; A woodcutter chops faster... modeled as a yield bonus (conditional effect).
  (:durative-action chop-wood
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (is-forest ?l)) (at start (has-axe ?a)))
    :effect (and (at end (increase (logs) 1))
                 (at end (when (woodcutter ?a) (increase (logs) 1)))))

  (:durative-action mine-ore
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (is-mine ?l)) (at start (has-pick ?a)))
    :effect (and (at end (increase (ore) 1))
                 (at end (when (miner ?a) (increase (ore) 1)))))

  (:durative-action quarry-stone
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (is-quarry ?l)) (at start (has-pick ?a)))
    :effect (at end (increase (stone) 1)))

  (:durative-action dig-clay
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (is-claypit ?l)) (at start (has-shovel ?a)))
    :effect (at end (increase (clay) 1)))

  (:durative-action draw-water
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 1)
    :condition (and (at start (at ?a ?l)) (at start (is-water ?l)))
    :effect (at end (increase (water) 1)))

  (:durative-action forage-food
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (or (is-field ?l) (is-forest ?l))))
    :effect (at end (increase (food) 1)))

  (:durative-action shear-fiber
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (is-pasture ?l)))
    :effect (at end (increase (fiber) 1)))

  (:durative-action gather-herbs
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (or (is-forest ?l) (is-field ?l))))
    :effect (at end (increase (herbs) 1)))

  ;; ========================= PROCESSING =========================
  (:durative-action saw-planks                  ; 1 log -> 2 planks
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (has-sawmill ?l)) (at start (>= (logs) 1)))
    :effect (and (at start (decrease (logs) 1)) (at end (increase (planks) 2))))

  (:durative-action burn-charcoal               ; 2 logs -> 1 charcoal
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-kiln ?l)) (at start (>= (logs) 2)))
    :effect (and (at start (decrease (logs) 2)) (at end (increase (charcoal) 1))))

  (:durative-action fire-bricks                 ; 2 clay -> 2 bricks
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-kiln ?l)) (at start (>= (clay) 2)))
    :effect (and (at start (decrease (clay) 2)) (at end (increase (bricks) 2))))

  (:durative-action smelt-ingot                 ; ore + charcoal -> ingot (smith bonus)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (has-forge ?l))
                    (at start (>= (ore) 1)) (at start (>= (charcoal) 1)))
    :effect (and (at start (decrease (ore) 1)) (at start (decrease (charcoal) 1))
                 (at end (increase (ingots) 1))
                 (at end (when (smith ?a) (increase (ingots) 1)))))

  (:durative-action mason-blocks                ; 1 stone -> 1 block (mason bonus)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (has-mason ?l)) (at start (>= (stone) 1)))
    :effect (and (at start (decrease (stone) 1))
                 (at end (increase (blocks) 1))
                 (at end (when (mason-skill ?a) (increase (blocks) 1)))))

  (:durative-action weave-cloth                 ; 2 fiber -> 1 cloth
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-loom ?l)) (at start (>= (fiber) 2)))
    :effect (and (at start (decrease (fiber) 2)) (at end (increase (cloth) 1))))

  (:durative-action tailor-clothing             ; 2 cloth -> 1 clothing
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-loom ?l)) (at start (>= (cloth) 2)))
    :effect (and (at start (decrease (cloth) 2)) (at end (increase (clothing) 1))))

  (:durative-action cook-meal                   ; food + water -> 2 meals (cook bonus)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (has-hearth ?l))
                    (at start (>= (food) 1)) (at start (>= (water) 1)))
    :effect (and (at start (decrease (food) 1)) (at start (decrease (water) 1))
                 (at end (increase (meals) 2))
                 (at end (when (cook ?a) (increase (meals) 1)))))

  ;; ========================= TOOLSMITHING =========================
  ;; Forge a tool into the shared stock; an agent then equips one.
  (:durative-action forge-axe
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-anvil ?l)) (at start (has-hammer ?a))
                    (at start (>= (ingots) 1)) (at start (>= (planks) 1)))
    :effect (and (at start (decrease (ingots) 1)) (at start (decrease (planks) 1))
                 (at end (increase (axe-stock) 1))))

  (:durative-action forge-pick
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-anvil ?l)) (at start (has-hammer ?a))
                    (at start (>= (ingots) 2)) (at start (>= (planks) 1)))
    :effect (and (at start (decrease (ingots) 2)) (at start (decrease (planks) 1))
                 (at end (increase (pick-stock) 1))))

  (:durative-action forge-shovel
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-anvil ?l)) (at start (has-hammer ?a))
                    (at start (>= (ingots) 1)) (at start (>= (planks) 1)))
    :effect (and (at start (decrease (ingots) 1)) (at start (decrease (planks) 1))
                 (at end (increase (shovel-stock) 1))))

  (:durative-action equip-axe
    :parameters (?a - agent)
    :duration (= ?duration 1)
    :condition (and (at start (>= (axe-stock) 1)) (at start (not (has-axe ?a))))
    :effect (and (at start (decrease (axe-stock) 1)) (at end (has-axe ?a))))

  (:durative-action equip-pick
    :parameters (?a - agent)
    :duration (= ?duration 1)
    :condition (and (at start (>= (pick-stock) 1)) (at start (not (has-pick ?a))))
    :effect (and (at start (decrease (pick-stock) 1)) (at end (has-pick ?a))))

  (:durative-action equip-shovel
    :parameters (?a - agent)
    :duration (= ?duration 1)
    :condition (and (at start (>= (shovel-stock) 1)) (at start (not (has-shovel ?a))))
    :effect (and (at start (decrease (shovel-stock) 1)) (at end (has-shovel ?a))))

  ;; ========================= ALCHEMY / MAGIC =========================
  (:durative-action meditate                    ; recover mana (mages only)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (has-altar ?l)) (at start (mage ?a)))
    :effect (at end (increase (mana) 2)))

  (:durative-action brew-potion                 ; herbs + water -> potion (costs mana)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-altar ?l)) (at start (mage ?a))
                    (at start (>= (herbs) 1)) (at start (>= (water) 1)) (at start (>= (mana) 1)))
    :effect (and (at start (decrease (herbs) 1)) (at start (decrease (water) 1))
                 (at start (decrease (mana) 1)) (at end (increase (potions) 1))))

  ;; ========================= CONSTRUCTION =========================
  (:durative-action build-well
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 5)
    :condition (and (at start (at ?a ?l)) (at start (is-buildsite ?l)) (at start (>= (blocks) 3)))
    :effect (and (at start (decrease (blocks) 3)) (at end (well-dug))))

  (:durative-action build-wall
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 6)
    :condition (and (at start (at ?a ?l)) (at start (is-buildsite ?l)) (at start (>= (blocks) 4)))
    :effect (and (at start (decrease (blocks) 4)) (at end (built-wall))))

  (:durative-action build-house
    :parameters (?a - agent ?l - location ?s - slot)
    :duration (= ?duration 6)
    :condition (and (at start (at ?a ?l)) (at start (is-buildsite ?l)) (at start (not (built-house ?s)))
                    (at start (>= (planks) 4)) (at start (>= (bricks) 2)))
    :effect (and (at start (decrease (planks) 4)) (at start (decrease (bricks) 2))
                 (at end (built-house ?s))))

  ;; The square caps the village: only once EVERY house slot is built (forall).
  (:durative-action build-square
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 5)
    :condition (and (at start (at ?a ?l)) (at start (is-buildsite ?l)) (at start (>= (blocks) 4))
                    (at start (forall (?s - slot) (built-house ?s))))
    :effect (and (at start (decrease (blocks) 4)) (at end (built-square))))

  ;; ========================= COMMUNITY / TRADE =========================
  ;; A feast at the hearth: consumes meals and feeds EVERY agent at that location
  ;; (forall + when over the concrete state).
  (:durative-action hold-feast
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (has-hearth ?l)) (at start (>= (meals) 3)))
    :effect (and (at start (decrease (meals) 3)) (at end (feast-held))))

  (:durative-action sell-goods                  ; turn surplus planks into coin
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 1)
    :condition (and (at start (at ?a ?l)) (at start (is-market ?l)) (at start (>= (planks) 2)))
    :effect (and (at start (decrease (planks) 2)) (at end (increase (coin) 1))))

  ;; ================= WIDENED SUBSYSTEMS =================
(:durative-action till-soil                   ; break a field with a shovel
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (is-field ?l)) (at start (has-shovel ?a))
                    (at start (not (tilled ?l))) (at start (not (planted ?l))))
    :effect (at end (tilled ?l)))
(:durative-action plant-seeds                 ; sow 1 seed into tilled soil
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (is-field ?l)) (at start (tilled ?l))
                    (at start (not (planted ?l))) (at start (>= (seeds) 1)))
    :effect (and (at start (decrease (seeds) 1))
                 (at end (not (tilled ?l))) (at end (planted ?l))))
(:durative-action irrigate-field              ; water a planted plot
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (is-field ?l)) (at start (planted ?l))
                    (at start (not (irrigated ?l))) (at start (>= (water) 1)))
    :effect (and (at start (decrease (water) 1)) (at end (irrigated ?l))))
(:durative-action harvest-grain
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (is-field ?l)) (at start (irrigated ?l)))
    :effect (and (at start (not (planted ?l))) (at start (not (irrigated ?l)))
                 (at end (increase (grain) 2)) (at end (increase (seeds) 1))
                 (at end (when (farmer ?a) (increase (grain) 1)))))
(:durative-action mill-flour                  ; 2 grain -> 3 flour at the mill
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-mill ?l)) (at start (>= (grain) 2)))
    :effect (and (at start (decrease (grain) 2)) (at end (increase (flour) 3))))
(:durative-action bake-bread                  ; 2 flour + water -> 2 bread (cook bonus)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (has-hearth ?l))
                    (at start (>= (flour) 2)) (at start (>= (water) 1)))
    :effect (and (at start (decrease (flour) 2)) (at start (decrease (water) 1))
                 (at end (increase (bread) 2))
                 (at end (when (cook ?a) (increase (bread) 1)))))
(:durative-action store-grain                 ; 3 grain -> 3 grain-reserve
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 1)
    :condition (and (at start (at ?a ?l)) (at start (has-granary ?l)) (at start (>= (grain) 3)))
    :effect (and (at start (decrease (grain) 3)) (at end (increase (grain-reserve) 3))))
(:durative-action mine-coal
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (is-coalmine ?l)) (at start (has-pick ?a)))
    :effect (and (at end (increase (coal) 1))
                 (at end (when (miner ?a) (increase (coal) 1)))))
(:durative-action mine-copper
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (is-coppermine ?l)) (at start (has-pick ?a)))
    :effect (and (at end (increase (copper-ore) 1))
                 (at end (when (miner ?a) (increase (copper-ore) 1)))))
(:durative-action mine-tin
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (is-tinmine ?l)) (at start (has-pick ?a)))
    :effect (and (at end (increase (tin-ore) 1))
                 (at end (when (miner ?a) (increase (tin-ore) 1)))))
(:durative-action mine-gold
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 5)
    :condition (and (at start (at ?a ?l)) (at start (is-goldmine ?l)) (at start (has-pick ?a)))
    :effect (at end (increase (gold-ore) 1)))
(:durative-action mine-silver
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 5)
    :condition (and (at start (at ?a ?l)) (at start (is-silvermine ?l)) (at start (has-pick ?a)))
    :effect (at end (increase (silver-ore) 1)))
(:durative-action smelt-copper             ; copper-ore + charcoal -> copper-ingot (smith bonus)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (has-forge ?l))
                    (at start (>= (copper-ore) 1)) (at start (>= (charcoal) 1)))
    :effect (and (at start (decrease (copper-ore) 1)) (at start (decrease (charcoal) 1))
                 (at end (increase (copper-ingot) 1))
                 (at end (when (smith ?a) (increase (copper-ingot) 1)))))
(:durative-action smelt-tin                ; tin-ore + charcoal -> tin-ingot (smith bonus)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (has-forge ?l))
                    (at start (>= (tin-ore) 1)) (at start (>= (charcoal) 1)))
    :effect (and (at start (decrease (tin-ore) 1)) (at start (decrease (charcoal) 1))
                 (at end (increase (tin-ingot) 1))
                 (at end (when (smith ?a) (increase (tin-ingot) 1)))))
(:durative-action alloy-bronze             ; copper-ingot + tin-ingot -> bronze
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (has-forge ?l))
                    (at start (>= (copper-ingot) 1)) (at start (>= (tin-ingot) 1)))
    :effect (and (at start (decrease (copper-ingot) 1)) (at start (decrease (tin-ingot) 1))
                 (at end (increase (bronze) 1))
                 (at end (when (metallurgist ?a) (increase (bronze) 1)))))
(:durative-action smelt-steel              ; ingots + coal -> steel
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 5)
    :condition (and (at start (at ?a ?l)) (at start (has-forge ?l))
                    (at start (>= (ingots) 1)) (at start (>= (coal) 1)))
    :effect (and (at start (decrease (ingots) 1)) (at start (decrease (coal) 1))
                 (at end (increase (steel) 1))
                 (at end (when (metallurgist ?a) (increase (steel) 1)))))
(:durative-action refine-gold-bullion      ; gold-ore + charcoal -> bullion (metallurgist bonus)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 5)
    :condition (and (at start (at ?a ?l)) (at start (has-anvil ?l)) (at start (has-hammer ?a))
                    (at start (>= (gold-ore) 1)) (at start (>= (charcoal) 1)))
    :effect (and (at start (decrease (gold-ore) 1)) (at start (decrease (charcoal) 1))
                 (at end (increase (bullion) 1))
                 (at end (when (metallurgist ?a) (increase (bullion) 1)))))
(:durative-action refine-silver-bullion    ; silver-ore + charcoal -> bullion
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (has-anvil ?l)) (at start (has-hammer ?a))
                    (at start (>= (silver-ore) 1)) (at start (>= (charcoal) 1)))
    :effect (and (at start (decrease (silver-ore) 1)) (at start (decrease (charcoal) 1))
                 (at end (increase (bullion) 1))))
(:durative-action mint-coin                ; bullion -> 5 coin
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (is-market ?l)) (at start (>= (bullion) 1)))
    :effect (and (at start (decrease (bullion) 1)) (at end (increase (coin) 5))))
(:durative-action grind-flour                 ; 2 grain -> 2 flour
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (has-mill ?l)) (at start (>= (grain) 2)))
    :effect (and (at start (decrease (grain) 2)) (at end (increase (flour) 2))))
(:durative-action cook-stew                   ; food (meat) + water -> 2 stew (cook bonus)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-hearth ?l))
                    (at start (>= (food) 1)) (at start (>= (water) 1)))
    :effect (and (at start (decrease (food) 1)) (at start (decrease (water) 1))
                 (at end (increase (stew) 2))
                 (at end (when (cook ?a) (increase (stew) 1)))))
(:durative-action bake-pie                    ; flour + food -> 1 pie (baker bonus)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-hearth ?l))
                    (at start (>= (flour) 1)) (at start (>= (food) 1)))
    :effect (and (at start (decrease (flour) 1)) (at start (decrease (food) 1))
                 (at end (increase (pies) 1))
                 (at end (when (baker ?a) (increase (pies) 1)))))
(:durative-action plate-spread                ; bread + stew + pie -> 3 meals
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (has-hearth ?l))
                    (at start (>= (bread) 1)) (at start (>= (stew) 1)) (at start (>= (pies) 1)))
    :effect (and (at start (decrease (bread) 1)) (at start (decrease (stew) 1))
                 (at start (decrease (pies) 1)) (at end (increase (meals) 3))))
(:durative-action hold-grand-feast
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-hearth ?l)) (at start (>= (meals) 4)))
    :effect (and (at start (decrease (meals) 4)) (at end (feast-held))
                 (at end (forall (?b - agent) (when (at ?b ?l) (well-fed ?b))))))
(:durative-action craft-timber-frame          ; 3 planks -> 1 timber-frame (builder bonus)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (has-sawmill ?l)) (at start (>= (planks) 3)))
    :effect (and (at start (decrease (planks) 3))
                 (at end (increase (timber-frame) 1))
                 (at end (when (builder ?a) (increase (timber-frame) 1)))))
(:durative-action craft-cut-fittings          ; 1 ingot -> 2 cut-fittings (builder bonus)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (has-anvil ?l)) (at start (has-hammer ?a))
                    (at start (>= (ingots) 1)))
    :effect (and (at start (decrease (ingots) 1))
                 (at end (increase (cut-fittings) 2))
                 (at end (when (builder ?a) (increase (cut-fittings) 1)))))
(:durative-action build-sawmill               ; frame + fittings + blocks
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 6)
    :condition (and (at start (at ?a ?l)) (at start (is-buildsite ?l)) (at start (builder ?a))
                    (at start (not (has-sawmill ?l)))
                    (at start (>= (timber-frame) 1)) (at start (>= (cut-fittings) 2))
                    (at start (>= (blocks) 2)))
    :effect (and (at start (decrease (timber-frame) 1)) (at start (decrease (cut-fittings) 2))
                 (at start (decrease (blocks) 2)) (at end (has-sawmill ?l))))
(:durative-action build-forge                 ; heavy: frame + fittings + bricks + stone
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 7)
    :condition (and (at start (at ?a ?l)) (at start (is-buildsite ?l)) (at start (builder ?a))
                    (at start (not (has-forge ?l)))
                    (at start (>= (timber-frame) 1)) (at start (>= (cut-fittings) 2))
                    (at start (>= (bricks) 3)) (at start (>= (stone) 2)))
    :effect (and (at start (decrease (timber-frame) 1)) (at start (decrease (cut-fittings) 2))
                 (at start (decrease (bricks) 3)) (at start (decrease (stone) 2))
                 (at end (has-forge ?l))))
(:durative-action build-anvil                 ; an anvil block beside a forge
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 5)
    :condition (and (at start (at ?a ?l)) (at start (is-buildsite ?l)) (at start (builder ?a))
                    (at start (not (has-anvil ?l)))
                    (at start (>= (cut-fittings) 2)) (at start (>= (blocks) 2)))
    :effect (and (at start (decrease (cut-fittings) 2)) (at start (decrease (blocks) 2))
                 (at end (has-anvil ?l))))
(:durative-action build-kiln                  ; bricks + blocks
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 6)
    :condition (and (at start (at ?a ?l)) (at start (is-buildsite ?l)) (at start (builder ?a))
                    (at start (not (has-kiln ?l)))
                    (at start (>= (bricks) 4)) (at start (>= (blocks) 2)))
    :effect (and (at start (decrease (bricks) 4)) (at start (decrease (blocks) 2))
                 (at end (has-kiln ?l))))
(:durative-action build-mason-shed            ; frame + stone + blocks
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 6)
    :condition (and (at start (at ?a ?l)) (at start (is-buildsite ?l)) (at start (builder ?a))
                    (at start (not (has-mason ?l)))
                    (at start (>= (timber-frame) 1)) (at start (>= (stone) 3))
                    (at start (>= (blocks) 1)))
    :effect (and (at start (decrease (timber-frame) 1)) (at start (decrease (stone) 3))
                 (at start (decrease (blocks) 1)) (at end (has-mason ?l))))
(:durative-action build-loom                  ; frame + fittings + planks
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 5)
    :condition (and (at start (at ?a ?l)) (at start (is-buildsite ?l)) (at start (builder ?a))
                    (at start (not (has-loom ?l)))
                    (at start (>= (timber-frame) 1)) (at start (>= (cut-fittings) 1))
                    (at start (>= (planks) 2)))
    :effect (and (at start (decrease (timber-frame) 1)) (at start (decrease (cut-fittings) 1))
                 (at start (decrease (planks) 2)) (at end (has-loom ?l))))
(:durative-action build-tannery               ; frame + planks + water-troughs (blocks)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 5)
    :condition (and (at start (at ?a ?l)) (at start (is-buildsite ?l)) (at start (builder ?a))
                    (at start (not (has-tannery ?l)))
                    (at start (>= (timber-frame) 1)) (at start (>= (planks) 2))
                    (at start (>= (blocks) 1)))
    :effect (and (at start (decrease (timber-frame) 1)) (at start (decrease (planks) 2))
                 (at start (decrease (blocks) 1)) (at end (has-tannery ?l))))
(:durative-action build-hearth                ; communal kitchen: bricks + blocks
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 5)
    :condition (and (at start (at ?a ?l)) (at start (is-buildsite ?l)) (at start (builder ?a))
                    (at start (not (has-hearth ?l)))
                    (at start (>= (bricks) 3)) (at start (>= (blocks) 1)))
    :effect (and (at start (decrease (bricks) 3)) (at start (decrease (blocks) 1))
                 (at end (has-hearth ?l))))
(:durative-action build-altar                 ; consecrated stone altar (stone + blocks)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 5)
    :condition (and (at start (at ?a ?l)) (at start (is-buildsite ?l)) (at start (builder ?a))
                    (at start (not (has-altar ?l)))
                    (at start (>= (stone) 2)) (at start (>= (blocks) 2)))
    :effect (and (at start (decrease (stone) 2)) (at start (decrease (blocks) 2))
                 (at end (has-altar ?l))))
(:durative-action build-watchtower
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 8)
    :condition (and (at start (at ?a ?l)) (at start (is-buildsite ?l)) (at start (builder ?a))
                    (at start (>= (timber-frame) 2)) (at start (>= (cut-fittings) 3))
                    (at start (>= (blocks) 6)))
    :effect (and (at start (decrease (timber-frame) 2)) (at start (decrease (cut-fittings) 3))
                 (at start (decrease (blocks) 6)) (at end (built-watchtower))))
(:durative-action build-temple
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 9)
    :condition (and (at start (at ?a ?l)) (at start (is-buildsite ?l)) (at start (builder ?a))
                    (at start (has-altar ?l)) (at start (priest ?a))
                    (at start (>= (timber-frame) 2)) (at start (>= (cut-fittings) 2))
                    (at start (>= (blocks) 5)) (at start (>= (bricks) 4)))
    :effect (and (at start (decrease (timber-frame) 2)) (at start (decrease (cut-fittings) 2))
                 (at start (decrease (blocks) 5)) (at start (decrease (bricks) 4))
                 (at end (built-temple))))
(:durative-action study-lore
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-hall ?l)))
    :effect (and (at end (increase (lore) 1))
                 (at end (when (master ?a) (increase (lore) 1)))))
(:durative-action train-woodcutter
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (has-hall ?l))
                    (at start (apprentice ?a)) (at start (not (woodcutter ?a)))
                    (at start (>= (lore) 2)))
    :effect (and (at start (decrease (lore) 2)) (at end (woodcutter ?a))))
(:durative-action train-smith
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (has-hall ?l))
                    (at start (apprentice ?a)) (at start (not (smith ?a)))
                    (at start (>= (lore) 2)))
    :effect (and (at start (decrease (lore) 2)) (at end (smith ?a))))
(:durative-action train-cook
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (has-hall ?l))
                    (at start (apprentice ?a)) (at start (not (cook ?a)))
                    (at start (>= (lore) 2)))
    :effect (and (at start (decrease (lore) 2)) (at end (cook ?a))))
(:durative-action attain-mastery
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 6)
    :condition (and (at start (at ?a ?l)) (at start (has-hall ?l))
                    (at start (not (master ?a)))
                    (at start (>= (lore) 4)) (at start (>= (renown) 1)))
    :effect (and (at start (decrease (lore) 4)) (at start (decrease (renown) 1))
                 (at end (master ?a))))
(:durative-action hold-market-day
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (is-market ?l))
                    (at start (>= (coin) 2)))
    :effect (and (at start (decrease (coin) 2))
                 (at end (increase (renown) 2))
                 (at end (market-day-held))
                 (at end (when (master ?a) (increase (renown) 1)))))
(:durative-action hold-festival
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (has-hall ?l))
                    (at start (>= (meals) 4)) (at start (>= (coin) 1))
                    (at start (forall (?b - agent) (or (not (at ?b ?l)) (at ?b ?l)))))
    :effect (and (at start (decrease (meals) 4)) (at start (decrease (coin) 1))
                 (at end (increase (renown) 3))
                 (at end (festival-held))
                 (at end (when (master ?a) (increase (renown) 2)))))
(:durative-action tan-hide                    ; 2 hide -> 1 leather (tanner bonus)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-tannery ?l)) (at start (>= (hide) 2)))
    :effect (and (at start (decrease (hide) 2))
                 (at end (increase (leather) 1))
                 (at end (when (tanner ?a) (increase (leather) 1)))))
(:durative-action craft-leather-armor         ; 3 leather -> 1 leather-armor
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (has-leather-bench ?l))
                    (at start (>= (leather) 3)))
    :effect (and (at start (decrease (leather) 3))
                 (at end (increase (leather-armor) 1))
                 (at end (made-armor))
                 (at end (when (leatherworker ?a) (increase (leather-armor) 1)))))
(:durative-action craft-leather-bag           ; 1 leather -> 1 bag
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (has-leather-bench ?l))
                    (at start (>= (leather) 1)))
    :effect (and (at start (decrease (leather) 1))
                 (at end (increase (bags) 1))
                 (at end (made-bag))
                 (at end (when (leatherworker ?a) (increase (bags) 1)))))
(:durative-action forge-sword                 ; 2 ingots + 1 plank -> sword (smith bonus)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (has-anvil ?l)) (at start (has-hammer ?a))
                    (at start (>= (ingots) 2)) (at start (>= (planks) 1)))
    :effect (and (at start (decrease (ingots) 2)) (at start (decrease (planks) 1))
                 (at end (increase (swords) 1))
                 (at end (when (smith ?a) (increase (swords) 1)))))
(:durative-action forge-spearhead             ; 1 ingot -> spearhead (smith bonus)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-anvil ?l)) (at start (has-hammer ?a))
                    (at start (>= (ingots) 1)))
    :effect (and (at start (decrease (ingots) 1))
                 (at end (increase (spearheads) 1))
                 (at end (when (smith ?a) (increase (spearheads) 1)))))
(:durative-action forge-arrowheads            ; 1 ingot -> 4 arrowheads (smith bonus +2)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-anvil ?l)) (at start (has-hammer ?a))
                    (at start (>= (ingots) 1)))
    :effect (and (at start (decrease (ingots) 1))
                 (at end (increase (arrowheads) 4))
                 (at end (when (smith ?a) (increase (arrowheads) 2)))))
(:durative-action forge-shield                ; 2 ingots + 2 planks -> shield
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (has-anvil ?l)) (at start (has-hammer ?a))
                    (at start (>= (ingots) 2)) (at start (>= (planks) 2)))
    :effect (and (at start (decrease (ingots) 2)) (at start (decrease (planks) 2))
                 (at end (increase (shields) 1))))
(:durative-action fletch-arrows               ; 4 arrowheads + 1 plank -> 4 arrows (fletcher +4)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (has-fletching-bench ?l))
                    (at start (>= (arrowheads) 4)) (at start (>= (planks) 1)))
    :effect (and (at start (decrease (arrowheads) 4)) (at start (decrease (planks) 1))
                 (at end (increase (arrows) 4))
                 (at end (when (fletcher ?a) (increase (arrows) 4)))))
(:durative-action feed-livestock
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (has-barn ?l))
                    (at start (>= (livestock) 1))
                    (at start (>= (grain) 1)) (at start (>= (water) 1)))
    :effect (and (at start (decrease (grain) 1)) (at start (decrease (water) 1))
                 (at end (increase (livestock) 1))
                 (at end (when (herder ?a) (increase (livestock) 1)))))
(:durative-action milk-livestock
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (has-barn ?l)) (at start (>= (livestock) 1)))
    :effect (and (at end (increase (dairy) 1))
                 (at end (when (herder ?a) (increase (dairy) 1)))))
(:durative-action shear-livestock
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (has-barn ?l)) (at start (>= (livestock) 1)))
    :effect (and (at end (increase (fiber) 1))
                 (at end (when (herder ?a) (increase (fiber) 1)))))
(:durative-action butcher-livestock
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-barn ?l)) (at start (>= (livestock) 1)))
    :effect (and (at start (decrease (livestock) 1))
                 (at end (increase (meat) 1)) (at end (increase (hide) 1))
                 (at end (when (herder ?a) (increase (meat) 1)))))
(:durative-action cure-meat
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (has-barn ?l)) (at start (>= (meat) 1)))
    :effect (and (at start (decrease (meat) 1)) (at end (increase (food) 1))))
(:durative-action forge-weapon
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-anvil ?l)) (at start (has-hammer ?a))
                    (at start (>= (ingots) 1)) (at start (>= (planks) 1)))
    :effect (and (at start (decrease (ingots) 1)) (at start (decrease (planks) 1))
                 (at end (increase (weapon-stock) 1))))
(:durative-action equip-weapon
    :parameters (?a - agent)
    :duration (= ?duration 1)
    :condition (and (at start (>= (weapon-stock) 1)) (at start (not (has-weapon ?a))))
    :effect (and (at start (decrease (weapon-stock) 1)) (at end (has-weapon ?a))))
(:durative-action train-guard
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (has-trainyard ?l))
                    (at start (not (guard ?a))) (at start (>= (meals) 1)))
    :effect (and (at start (decrease (meals) 1)) (at end (guard ?a))))
(:durative-action defend-location
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 5)
    :condition (and (at start (at ?a ?l)) (at start (threat ?l)) (at start (has-weapon ?a))
                    (at start (>= (ration) 1)))
    :effect (and (at start (decrease (ration) 1))
                 (at start (not (threat ?l)))
                 (at end (cleared ?l))
                 (at end (when (guard ?a) (increase (ration) 1)))))
(:durative-action pack-rations
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 1)
    :condition (and (at start (at ?a ?l)) (at start (has-hearth ?l)) (at start (>= (meals) 1)))
    :effect (and (at start (decrease (meals) 1)) (at end (increase (ration) 2))))
(:durative-action dig-sand
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (is-sandpit ?l)) (at start (has-shovel ?a)))
    :effect (at end (increase (sand) 1)))
(:durative-action melt-glass
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-kiln ?l)) (at start (>= (sand) 2)))
    :effect (and (at start (decrease (sand) 2)) (at end (increase (glass) 1))))
(:durative-action throw-pottery
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (has-wheel ?l)) (at start (>= (clay) 1)))
    :effect (and (at start (decrease (clay) 1))
                 (at end (increase (pottery) 1))
                 (at end (when (potter ?a) (increase (pottery) 1)))))
(:durative-action fire-pottery
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-kiln ?l)) (at start (>= (pottery) 1)))
    :effect (and (at start (decrease (pottery) 1)) (at end (increase (fired-pottery) 1))))
(:durative-action hunt-game
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (is-forest ?l))
                    (at start (or (has-bow ?a) (has-spear ?a))))
    :effect (and (at end (increase (meat) 1))
                 (at end (increase (hide) 1))
                 (at end (increase (bone) 1))
                 (at end (when (hunter ?a) (increase (meat) 1)))))
(:durative-action set-trap
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (is-forest ?l)) (at start (not (trap-set ?l))))
    :effect (at end (trap-set ?l)))
(:durative-action check-trap
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (trap-set ?l)))
    :effect (and (at start (not (trap-set ?l)))
                 (at end (increase (meat) 1))
                 (at end (increase (hide) 1))
                 (at end (when (hunter ?a) (increase (hide) 1)))))
(:durative-action fish-water
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (is-water ?l)) (at start (has-spear ?a)))
    :effect (and (at end (increase (fish) 1))
                 (at end (when (angler ?a) (increase (fish) 1)))))
(:durative-action craft-bow
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-sawmill ?l))
                    (at start (>= (planks) 1)) (at start (>= (fiber) 1)))
    :effect (and (at start (decrease (planks) 1)) (at start (decrease (fiber) 1))
                 (at end (increase (bow-stock) 1))))
(:durative-action forge-spear
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-anvil ?l)) (at start (has-hammer ?a))
                    (at start (>= (ingots) 1)) (at start (>= (planks) 1)))
    :effect (and (at start (decrease (ingots) 1)) (at start (decrease (planks) 1))
                 (at end (increase (spear-stock) 1))))
(:durative-action equip-bow
    :parameters (?a - agent)
    :duration (= ?duration 1)
    :condition (and (at start (>= (bow-stock) 1)) (at start (not (has-bow ?a))))
    :effect (and (at start (decrease (bow-stock) 1)) (at end (has-bow ?a))))
(:durative-action equip-spear
    :parameters (?a - agent)
    :duration (= ?duration 1)
    :condition (and (at start (>= (spear-stock) 1)) (at start (not (has-spear ?a))))
    :effect (and (at start (decrease (spear-stock) 1)) (at end (has-spear ?a))))
(:durative-action shape-cart-parts            ; 2 planks -> 2 cart-parts
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (has-sawmill ?l)) (at start (>= (planks) 2)))
    :effect (and (at start (decrease (planks) 2)) (at end (increase (cart-parts) 2))))
(:durative-action build-cart                  ; 2 cart-parts + 1 ingot -> 1 cart
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-cartwright ?l))
                    (at start (>= (cart-parts) 2)) (at start (>= (ingots) 1)))
    :effect (and (at start (decrease (cart-parts) 2)) (at start (decrease (ingots) 1))
                 (at end (increase (carts) 1))))
(:durative-action equip-cart
    :parameters (?a - agent)
    :duration (= ?duration 1)
    :condition (and (at start (>= (carts) 1)) (at start (not (has-cart ?a))))
    :effect (and (at start (decrease (carts) 1)) (at end (has-cart ?a))))
(:durative-action raise-pack-animal           ; food -> 1 pack-animal, +1 carry-cap
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (is-pasture ?l)) (at start (>= (food) 2)))
    :effect (and (at start (decrease (food) 2))
                 (at end (increase (pack-animals) 1))
                 (at end (increase (carry-cap) 1))))
(:durative-action load-cargo                  ; planks -> cargo (capped, porter bonus)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (has-depot ?l)) (at start (has-cart ?a))
                    (at start (>= (planks) 1)) (at start (>= (carry-cap) 1)))
    :effect (and (at start (decrease (planks) 1)) (at end (increase (cargo) 1))
                 (at end (when (porter ?a) (increase (cargo) 1)))))
(:durative-action haul-cargo                  ; cargo -> planks (delivered) + coin
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (has-depot ?l)) (at start (has-cart ?a))
                    (at start (>= (cargo) 1)) (at start (>= (carry-cap) 1)))
    :effect (and (at start (decrease (cargo) 1))
                 (at end (increase (planks) 1)) (at end (increase (coin) 1))
                 (at end (when (porter ?a) (increase (planks) 1)))))
(:durative-action build-furniture            ; 3 planks -> 1 furniture (carpenter bonus)
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (has-carpenter-bench ?l))
                    (at start (has-hammer ?a)) (at start (>= (planks) 3)))
    :effect (and (at start (decrease (planks) 3))
                 (at end (increase (furniture) 1))
                 (at end (when (carpenter ?a) (increase (furniture) 1)))))
(:durative-action coopered-barrel            ; 2 planks -> 1 barrel
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-carpenter-bench ?l))
                    (at start (has-hammer ?a)) (at start (>= (planks) 2)))
    :effect (and (at start (decrease (planks) 2))
                 (at end (increase (barrels) 1))
                 (at end (when (carpenter ?a) (increase (barrels) 1)))))
(:durative-action carve-handles              ; 1 plank -> 2 tool-handles
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (has-carpenter-bench ?l))
                    (at start (has-hammer ?a)) (at start (>= (planks) 1)))
    :effect (and (at start (decrease (planks) 1))
                 (at end (increase (tool-handles) 2))))
(:durative-action assemble-cart-parts        ; 4 planks + 1 tool-handle -> 1 cart-part
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 5)
    :condition (and (at start (at ?a ?l)) (at start (has-carpenter-bench ?l))
                    (at start (has-hammer ?a))
                    (at start (>= (planks) 4)) (at start (>= (tool-handles) 1)))
    :effect (and (at start (decrease (planks) 4)) (at start (decrease (tool-handles) 1))
                 (at end (increase (cart-parts) 1))
                 (at end (when (carpenter ?a) (increase (cart-parts) 1)))))
(:durative-action grow-mana-crystal           ; 3 mana -> mana-crystal
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (has-crystal-bed ?l)) (at start (mage ?a))
                    (at start (>= (mana) 3)))
    :effect (and (at start (decrease (mana) 3))
                 (at end (increase (mana-crystals) 1))
                 (at end (when (enchanter ?a) (increase (mana-crystals) 1)))))
(:durative-action inscribe-scroll             ; mana-crystal + cloth + 1 mana -> scroll
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-scribe-desk ?l)) (at start (mage ?a))
                    (at start (>= (mana-crystals) 1)) (at start (>= (cloth) 1)) (at start (>= (mana) 1)))
    :effect (and (at start (decrease (mana-crystals) 1)) (at start (decrease (cloth) 1))
                 (at start (decrease (mana) 1)) (at end (increase (scrolls) 1))))
(:durative-action enchant-gear                ; axe-stock + potion + 2 mana -> enchanted-gear
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 4)
    :condition (and (at start (at ?a ?l)) (at start (has-enchant-altar ?l)) (at start (mage ?a))
                    (at start (>= (axe-stock) 1)) (at start (>= (potions) 1)) (at start (>= (mana) 2)))
    :effect (and (at start (decrease (axe-stock) 1)) (at start (decrease (potions) 1))
                 (at start (decrease (mana) 2))
                 (at end (increase (enchanted-gear) 1))
                 (at end (when (enchanter ?a) (increase (enchanted-gear) 1)))))
(:durative-action brew-draught                ; potion + herbs + 1 mana -> draught
    :parameters (?a - agent ?l - location)
    :duration (= ?duration 3)
    :condition (and (at start (at ?a ?l)) (at start (has-enchant-altar ?l)) (at start (mage ?a))
                    (at start (>= (potions) 1)) (at start (>= (herbs) 2)) (at start (>= (mana) 1)))
    :effect (and (at start (decrease (potions) 1)) (at start (decrease (herbs) 2))
                 (at start (decrease (mana) 1)) (at end (increase (draughts) 1))))
(:durative-action mend-worker                 ; draught -> cure (injured ?p)
    :parameters (?a ?p - agent ?l - location)
    :duration (= ?duration 2)
    :condition (and (at start (at ?a ?l)) (at start (at ?p ?l)) (at start (has-enchant-altar ?l))
                    (at start (mage ?a)) (at start (injured ?p)) (at start (>= (draughts) 1)))
    :effect (and (at start (decrease (draughts) 1)) (at end (not (injured ?p)))))
)
