;; DEEP TRAVEL: a 12-node corridor, no shortcuts
(define (problem corridor-12) (:domain rpg-world)
  (:objects n0 n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 n11 - location  a0 - agent)
  (:init
    (at a0 n0)
    (has-axe a0) (has-pick a0) (has-shovel a0) (has-hammer a0) (woodcutter a0) (miner a0) (smith a0) (mason-skill a0) (cook a0) (mage a0) (farmer a0) (metallurgist a0) (baker a0) (well-fed a0) (builder a0) (priest a0) (apprentice a0) (master a0) (tanner a0) (leatherworker a0) (fletcher a0) (herder a0) (has-weapon a0) (guard a0) (potter a0) (has-bow a0) (has-spear a0) (hunter a0) (angler a0) (porter a0) (has-cart a0) (carpenter a0) (enchanter a0) (injured a0)
    (link n0 n1) (= (dist n0 n1) 1) (link n1 n0) (= (dist n1 n0) 1) (link n1 n2) (= (dist n1 n2) 1) (link n2 n1) (= (dist n2 n1) 1) (link n2 n3) (= (dist n2 n3) 1) (link n3 n2) (= (dist n3 n2) 1) (link n3 n4) (= (dist n3 n4) 1) (link n4 n3) (= (dist n4 n3) 1)
    (link n4 n5) (= (dist n4 n5) 1) (link n5 n4) (= (dist n5 n4) 1) (link n5 n6) (= (dist n5 n6) 1) (link n6 n5) (= (dist n6 n5) 1) (link n6 n7) (= (dist n6 n7) 1) (link n7 n6) (= (dist n7 n6) 1) (link n7 n8) (= (dist n7 n8) 1) (link n8 n7) (= (dist n8 n7) 1)
    (link n8 n9) (= (dist n8 n9) 1) (link n9 n8) (= (dist n9 n8) 1) (link n9 n10) (= (dist n9 n10) 1) (link n10 n9) (= (dist n10 n9) 1) (link n10 n11) (= (dist n10 n11) 1) (link n11 n10) (= (dist n11 n10) 1)
    (= (arrowheads) 0)
    (= (arrows) 0)
    (= (axe-stock) 0)
    (= (bags) 0)
    (= (barrels) 0)
    (= (blocks) 0)
    (= (bone) 0)
    (= (bow-stock) 0)
    (= (bread) 0)
    (= (bricks) 0)
    (= (bronze) 0)
    (= (bullion) 0)
    (= (cargo) 0)
    (= (carry-cap) 0)
    (= (cart-parts) 0)
    (= (carts) 0)
    (= (charcoal) 0)
    (= (clay) 0)
    (= (cloth) 0)
    (= (clothing) 0)
    (= (coal) 0)
    (= (coin) 0)
    (= (copper-ingot) 0)
    (= (copper-ore) 0)
    (= (cut-fittings) 0)
    (= (dairy) 0)
    (= (draughts) 0)
    (= (enchanted-gear) 0)
    (= (fiber) 0)
    (= (fired-pottery) 0)
    (= (fish) 0)
    (= (flour) 0)
    (= (food) 0)
    (= (furniture) 0)
    (= (glass) 0)
    (= (gold-ore) 0)
    (= (grain) 0)
    (= (grain-reserve) 0)
    (= (hammer-stock) 0)
    (= (herbs) 0)
    (= (hide) 0)
    (= (ingots) 0)
    (= (leather) 0)
    (= (leather-armor) 0)
    (= (livestock) 0)
    (= (logs) 0)
    (= (lore) 0)
    (= (mana) 0)
    (= (mana-crystals) 0)
    (= (meals) 0)
    (= (meat) 0)
    (= (ore) 0)
    (= (pack-animals) 0)
    (= (pick-stock) 0)
    (= (pies) 0)
    (= (planks) 0)
    (= (potions) 0)
    (= (pottery) 0)
    (= (ration) 0)
    (= (renown) 0)
    (= (resources) 0)
    (= (sand) 0)
    (= (scrolls) 0)
    (= (seeds) 0)
    (= (shields) 0)
    (= (shovel-stock) 0)
    (= (silver-ore) 0)
    (= (spear-stock) 0)
    (= (spearheads) 0)
    (= (steel) 0)
    (= (stew) 0)
    (= (stone) 0)
    (= (swords) 0)
    (= (timber-frame) 0)
    (= (tin-ingot) 0)
    (= (tin-ore) 0)
    (= (tool-handles) 0)
    (= (water) 0)
    (= (weapon-stock) 0)
  )
  (:goal (and (at a0 n11))))
