;; BIG CONJUNCTION: an 8-part order
(define (problem order-8) (:domain rpg-world)
  (:objects a0 - agent  hub - location)
  (:init
    (at a0 hub)
    (is-forest hub) (is-mine hub) (is-quarry hub) (is-claypit hub) (is-water hub) (is-pasture hub) (is-field hub) (is-market hub) (has-sawmill hub) (has-kiln hub) (has-forge hub) (has-anvil hub) (has-mason hub) (has-loom hub) (has-hearth hub) (has-altar hub) (is-buildsite hub) (has-mill hub) (has-granary hub) (is-coalmine hub) (is-coppermine hub) (is-tinmine hub) (is-goldmine hub) (is-silvermine hub) (has-hall hub) (has-tannery hub) (has-leather-bench hub) (has-fletching-bench hub) (has-barn hub) (has-trainyard hub) (has-watchtower hub) (is-sandpit hub) (has-wheel hub) (has-cartwright hub) (has-depot hub) (has-carpenter-bench hub) (has-enchant-altar hub) (has-scribe-desk hub) (has-crystal-bed hub)
    (has-axe a0) (has-pick a0) (has-shovel a0) (has-hammer a0) (woodcutter a0) (miner a0) (smith a0) (mason-skill a0) (cook a0) (mage a0) (farmer a0) (metallurgist a0) (baker a0) (well-fed a0) (builder a0) (priest a0) (apprentice a0) (master a0) (tanner a0) (leatherworker a0) (fletcher a0) (herder a0) (has-weapon a0) (guard a0) (potter a0) (has-bow a0) (has-spear a0) (hunter a0) (angler a0) (porter a0) (has-cart a0) (carpenter a0) (enchanter a0) (injured a0)
    (= (arrowheads) 0)
    (= (arrows) 0)
    (= (axe-stock) 0)
    (= (bags) 0)
    (= (barrels) 0)
    (= (blocks) 0)
    (= (bone) 0)
    (= (bow-stock) 0)
    (= (bread) 0)
    (= (bricks) 0)
    (= (bronze) 0)
    (= (bullion) 0)
    (= (cargo) 0)
    (= (carry-cap) 0)
    (= (cart-parts) 0)
    (= (carts) 0)
    (= (charcoal) 10)
    (= (clay) 10)
    (= (cloth) 0)
    (= (clothing) 0)
    (= (coal) 0)
    (= (coin) 0)
    (= (copper-ingot) 0)
    (= (copper-ore) 0)
    (= (cut-fittings) 0)
    (= (dairy) 0)
    (= (draughts) 0)
    (= (enchanted-gear) 0)
    (= (fiber) 10)
    (= (fired-pottery) 0)
    (= (fish) 0)
    (= (flour) 0)
    (= (food) 10)
    (= (furniture) 0)
    (= (glass) 0)
    (= (gold-ore) 0)
    (= (grain) 0)
    (= (grain-reserve) 0)
    (= (hammer-stock) 0)
    (= (herbs) 6)
    (= (hide) 0)
    (= (ingots) 0)
    (= (leather) 0)
    (= (leather-armor) 0)
    (= (livestock) 0)
    (= (logs) 16)
    (= (lore) 0)
    (= (mana) 4)
    (= (mana-crystals) 0)
    (= (meals) 0)
    (= (meat) 0)
    (= (ore) 10)
    (= (pack-animals) 0)
    (= (pick-stock) 0)
    (= (pies) 0)
    (= (planks) 0)
    (= (potions) 0)
    (= (pottery) 0)
    (= (ration) 0)
    (= (renown) 0)
    (= (resources) 0)
    (= (sand) 0)
    (= (scrolls) 0)
    (= (seeds) 0)
    (= (shields) 0)
    (= (shovel-stock) 0)
    (= (silver-ore) 0)
    (= (spear-stock) 0)
    (= (spearheads) 0)
    (= (steel) 0)
    (= (stew) 0)
    (= (stone) 10)
    (= (swords) 0)
    (= (timber-frame) 0)
    (= (tin-ingot) 0)
    (= (tin-ore) 0)
    (= (tool-handles) 0)
    (= (water) 10)
    (= (weapon-stock) 0)
  )
  (:goal (and (>= (ingots) 2) (>= (blocks) 2) (>= (planks) 4) (>= (cloth) 1) (>= (meals) 2) (>= (bricks) 2) (>= (clothing) 1) (>= (potions) 1))))
