//! The barter think benchmark (0.13 Phase 3) — generates
//! `benchmarks/bazaar-thinks.md`. The corpus was the planner's measuring
//! stick; this is the game track's: bazaar thinks measured END-TO-END on
//! the vendored wants-gated chain fixture (`benchmarks/bench/
//! bazaar-chain*.pddl`), where the goal `(has a0 item-k)` forces a k-hop
//! trade-up chain (every trade crosses exactly one want-edge, so ANY plan
//! spends >= k trades; junk inventory makes wrong picks dead ends).
//!
//! One world, forked minds (Phase 1+2 in anger): the world grounds ONCE;
//! every (depth, budget) cell is a `fork` + `set_goal` + one bounded
//! think. Whatever the curves say, they ship.
//!
//! Run: cargo run --release -p ferroplan --example bazaar_thinks \
//!        > benchmarks/bazaar-thinks.md
use ferroplan::{Options, Session};
use std::time::Instant;

const DOM: &str = include_str!("../../../benchmarks/bench/bazaar-chain-domain.pddl");
const PRB: &str = include_str!("../../../benchmarks/bench/bazaar-chain.pddl");
const PRB_X2: &str = include_str!("../../../benchmarks/bench/bazaar-chain-x2.pddl");

const DEPTHS: [usize; 8] = [1, 2, 3, 4, 6, 8, 10, 11];

/// One depth x budget sweep over a grounded world: every cell is a forked
/// mind + `set_goal(goal(k))` + ONE bounded think. Returns (depth, first
/// solving budget) per depth for the onset report.
fn sweep(
    world: &Session,
    budgets: &[usize],
    goal: impl Fn(usize) -> String,
) -> Result<Vec<(usize, Option<usize>)>, String> {
    print!("| depth k |");
    for b in budgets {
        print!(" B={b} |");
    }
    println!(" think ms (max B) |");
    print!("|---|");
    for _ in budgets {
        print!("---|");
    }
    println!("---|");
    let mut onset = Vec::new();
    for k in DEPTHS {
        print!("| {k} |");
        let mut first_solving = None;
        let mut big_ms = 0.0;
        for &b in budgets {
            let mut mind = world.fork();
            mind.set_goal(&goal(k))?;
            let t = Instant::now();
            let think = mind.replan_budgeted(b, Some(256));
            let ms = t.elapsed().as_secs_f64() * 1e3;
            if b == budgets[budgets.len() - 1] {
                big_ms = ms;
            }
            if think.solved {
                first_solving.get_or_insert(b);
                print!(
                    " {} @ {} |",
                    think.plan.as_ref().unwrap().length,
                    think.statistics.evaluated_states
                );
            } else {
                print!(" -- |");
            }
        }
        println!(" {big_ms:.1} |");
        onset.push((k, first_solving));
    }
    println!();
    println!("Where budget-exhausted verdicts begin:");
    println!();
    for (k, b) in &onset {
        match b {
            Some(b) => println!("- depth {k}: solves from B={b}"),
            None => println!("- depth {k}: UNSOLVED at every budget in the ladder"),
        }
    }
    Ok(onset)
}

fn main() -> Result<(), String> {
    let t = Instant::now();
    let world = Session::new(DOM, PRB, &Options::default())?;
    let ground_s = t.elapsed().as_secs_f64();

    println!("# Bazaar thinks — the game track's scoreboard");
    println!();
    println!("Generated by `cargo run --release -p ferroplan --example bazaar_thinks`");
    println!("(0.13 Phase 3). Fixtures: `benchmarks/bench/bazaar-chain*.pddl` — 12");
    println!("holders x 40 items, wants-gated barter; goal depth k forces a k-hop");
    println!("trade-up chain (every trade crosses one want-edge, so ANY plan spends");
    println!(">= k trades per chain; junk picks strand the chain item). The world");
    println!("grounds ONCE per fixture; each cell below is an independent forked");
    println!("mind: `fork` + `set_goal` + ONE bounded think (`replan_budgeted(B,");
    println!("256 MB)`) — eval budgets, so thinks are deterministic at any thread");
    println!("count. Cell = `plan-length @ evals-spent`, `--` = honest");
    println!("budget-exhausted verdict. Whatever the curves say, they ship.");
    println!();
    println!("## Solo chains: heuristic-transparent (a finding, not a failure)");
    println!();
    println!("A single trade-up chain is EXACTLY visible to the relaxed-plan");
    println!("heuristic (relaxation never spends the offered item, but a solo");
    println!("chain never needs it back), so every depth solves at k+1 evals in");
    println!("well under a millisecond — an NPC can chase an 11-hop trade chain");
    println!("EVERY TICK. That is the game-track headline.");
    println!();
    sweep(&world, &[250, 1_000, 4_000, 16_000, 64_000], |k| {
        format!("(has a0 item{k})")
    })?;

    println!();
    println!("## Contended chains: where the curves live");
    println!();
    println!("`bazaar-chain-x2`: TWO chains cross at every vendor (v-j holds A-j");
    println!("and B-j, wants A-(j-1) and B-(j-1)), both fed from one mind's two");
    println!("seeds; goal k wants BOTH depth-k items (>= 2k trades). The");
    println!("relaxation cannot see the contention — one offered item \"advances\"");
    println!("both chains at once in relaxed space — so real search must dodge");
    println!("cross-picks that strand a chain. Budget-exhausted verdicts appear");
    println!("here.");
    println!();
    let t = Instant::now();
    let world_x2 = Session::new(DOM, PRB_X2, &Options::default())?;
    let ground_x2_s = t.elapsed().as_secs_f64();
    sweep(&world_x2, &[1_000, 4_000, 16_000, 64_000, 256_000], |k| {
        format!("(and (has a0 itemA{k}) (has a0 itemB{k}))")
    })?;

    let mind = world_x2.fork();
    println!();
    println!("## Per-mind retained memory and world load");
    println!();
    println!(
        "- shared world payload (once, however many minds): ~{:.1} MB solo / \
         ~{:.1} MB contended",
        world.fork().world_bytes() as f64 / 1e6,
        mind.world_bytes() as f64 / 1e6
    );
    println!(
        "- private state per forked mind: ~{:.2} KB",
        mind.mind_bytes() as f64 / 1e3
    );
    println!(
        "- world load: {ground_s:.2} s solo / {ground_x2_s:.2} s contended, once; \
         forks are O(state-copy) — see the `many_minds` example for the \
         12-NPC load story"
    );
    Ok(())
}
